import { loadUnifiedReport } from "../lib/voiceState";

export function ReportPage() {
  const report = loadUnifiedReport<any>();

  return (
    <section className="card">
      <h2>Unified Report</h2>
      <p className="muted">This report is generated by the voice command center in agent mode.</p>
      <pre className="output-box">{report ? JSON.stringify(report, null, 2) : "No report generated yet. Say: generate report"}</pre>
    </section>
  );
}
